services:
  - type: static
    name: dashboarder-frontend
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://dashboarder-api.onrender.com/api

  - type: web
    name: dashboarder-api
    runtime: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    plan: free
